# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

# authors

a1 = Author.create(name: 'Alice')
a2 = Author.create(name: 'Bob')
a3 = Author.create(name: 'Cindy')
a4 = Author.create(name: 'Donald')
a5 = Author.create(name: 'Edith')

# items

a1.items.create(name: 'Monday', group_id: 1, views: 0)
a1.items.create(name: 'Tuesday', group_id: 1, views: 0)
a1.items.create(name: 'Wednesday', group_id: 1, views: 0)
a1.items.create(name: 'Thursday', group_id: 1, views: 0)
a1.items.create(name: 'Friday', group_id: 1, views: 0)
a1.items.create(name: 'Saturday', group_id: 1, views: 0)
a1.items.create(name: 'Sunday', group_id: 1, views: 0)

a1.items.create(name: 'January', group_id: 2, views: 0)
a1.items.create(name: 'February', group_id: 2, views: 0)
a1.items.create(name: 'March', group_id: 2, views: 0)
a1.items.create(name: 'April', group_id: 2, views: 0)
a1.items.create(name: 'May', group_id: 2, views: 0)
a1.items.create(name: 'June', group_id: 2, views: 0)
a1.items.create(name: 'July', group_id: 2, views: 0)
a1.items.create(name: 'August', group_id: 2, views: 0)
a1.items.create(name: 'September', group_id: 2, views: 0)
a1.items.create(name: 'October', group_id: 2, views: 0)
a1.items.create(name: 'November', group_id: 2, views: 0)
a1.items.create(name: 'December', group_id: 2, views: 0)

a2.items.create(name: 'Piccolo', group_id: 3, views: 0)
a2.items.create(name: 'Quarter', group_id: 3, views: 0)
a2.items.create(name: 'Chopine', group_id: 3, views: 0)
a2.items.create(name: 'Demi', group_id: 3, views: 0)
a2.items.create(name: 'Tenth', group_id: 3, views: 0)
a2.items.create(name: 'Jennie', group_id: 3, views: 0)
a2.items.create(name: 'Clavelin', group_id: 3, views: 0)
a2.items.create(name: 'Standard', group_id: 3, views: 0)
a2.items.create(name: 'Fifth', group_id: 3, views: 0)
a2.items.create(name: 'Litre', group_id: 3, views: 0)
a2.items.create(name: 'Magnum', group_id: 3, views: 0)
a2.items.create(name: 'Marie Jeanne', group_id: 3, views: 0)
a2.items.create(name: 'Jeroboam', group_id: 3, views: 0)
a2.items.create(name: 'Rehoboam', group_id: 3, views: 0)
a2.items.create(name: 'Imperial', group_id: 3, views: 0)
a2.items.create(name: 'Methuselah', group_id: 3, views: 0)
a2.items.create(name: 'Salmanazar', group_id: 3, views: 0)
a2.items.create(name: 'Nebuchadnezzar', group_id: 3, views: 0)
a2.items.create(name: 'Melchior', group_id: 3, views: 0)
a2.items.create(name: 'Solomon', group_id: 3, views: 0)
a2.items.create(name: 'Sovereign', group_id: 3, views: 0)
a2.items.create(name: 'Goliath', group_id: 3, views: 0)
a2.items.create(name: 'Midas', group_id: 3, views: 0)

a2.items.create(name: 'King', group_id: 4, views: 0)
a2.items.create(name: 'Queen', group_id: 4, views: 0)
a2.items.create(name: 'Royal Duke', group_id: 4, views: 0)
a2.items.create(name: 'Duchess', group_id: 4, views: 0)
a2.items.create(name: 'Archbishop', group_id: 4, views: 0)
a2.items.create(name: 'Duke', group_id: 4, views: 0)
a2.items.create(name: 'Duchess', group_id: 4, views: 0)
a2.items.create(name: 'Marquess', group_id: 4, views: 0)
a2.items.create(name: 'Marchioness', group_id: 4, views: 0)
a2.items.create(name: 'Earl', group_id: 4, views: 0)
a2.items.create(name: 'Countess', group_id: 4, views: 0)
a2.items.create(name: 'Viscount', group_id: 4, views: 0)
a2.items.create(name: 'Viscountess', group_id: 4, views: 0)
a2.items.create(name: 'Bishop', group_id: 4, views: 0)
a2.items.create(name: 'Baron', group_id: 4, views: 0)
a2.items.create(name: 'Baroness', group_id: 4, views: 0)

a3.items.create(name: 'Aries', group_id: 5, views: 0)
a3.items.create(name: 'Taurus', group_id: 5, views: 0)
a3.items.create(name: 'Gemini', group_id: 5, views: 0)
a3.items.create(name: 'Cancer', group_id: 5, views: 0)
a3.items.create(name: 'Leo', group_id: 5, views: 0)
a3.items.create(name: 'Virgo', group_id: 5, views: 0)
a3.items.create(name: 'Libra', group_id: 5, views: 0)
a3.items.create(name: 'Scorpio', group_id: 5, views: 0)
a3.items.create(name: 'Sagittarius', group_id: 5, views: 0)
a3.items.create(name: 'Capricorn', group_id: 5, views: 0)
a3.items.create(name: 'Aquarius', group_id: 5, views: 0)
a3.items.create(name: 'Pisces', group_id: 5, views: 0)

a3.items.create(name: "Carol Ann Duffy", group_id: 6, views: 0)
a3.items.create(name: "Andrew Motion", group_id: 6, views: 0)
a3.items.create(name: "Edward (Ted) Hughes", group_id: 6, views: 0)
a3.items.create(name: "Sir John Betjeman", group_id: 6, views: 0)
a3.items.create(name: "Cecil Day Lewis", group_id: 6, views: 0)
a3.items.create(name: "John Masefield", group_id: 6, views: 0)
a3.items.create(name: "Robert Bridges", group_id: 6, views: 0)
a3.items.create(name: "Alfred Austin", group_id: 6, views: 0)
a3.items.create(name: "Alfred Lord Tennyson", group_id: 6, views: 0)
a3.items.create(name: "William Wordsworth", group_id: 6, views: 0)
a3.items.create(name: "Robert Southey", group_id: 6, views: 0)
a3.items.create(name: "Henry James Pye", group_id: 6, views: 0)
a3.items.create(name: "Thomas Warton", group_id: 6, views: 0)
a3.items.create(name: "William Whiteheed", group_id: 6, views: 0)
a3.items.create(name: "Colley Cibber", group_id: 6, views: 0)
a3.items.create(name: "Rev. Laurence Eusden", group_id: 6, views: 0)
a3.items.create(name: "Nicholas Rowe", group_id: 6, views: 0)
a3.items.create(name: "Nathan Tate", group_id: 6, views: 0)
a3.items.create(name: "Thomas Shadwall", group_id: 6, views: 0)
a3.items.create(name: "John Dryden", group_id: 6, views: 0)
a3.items.create(name: "Sir William d’Avenant", group_id: 6, views: 0)
a3.items.create(name: "Ben Jonson", group_id: 6, views: 0)
a3.items.create(name: "Samuel Daniel", group_id: 6, views: 0)

a4.items.create(name: 'Barack Hussein Obama', group_id: 7, views: 0)
a4.items.create(name: 'George Walker “W” Bush', group_id: 7, views: 0)
a4.items.create(name: 'William (Bill) Jefferson Clinton', group_id: 7, views: 0)
a4.items.create(name: 'George Herbert Walker Bush', group_id: 7, views: 0)
a4.items.create(name: 'Ronald Reagan', group_id: 7, views: 0)
a4.items.create(name: 'James (Jimmy) Carter', group_id: 7, views: 0)
a4.items.create(name: 'Gerald Ford', group_id: 7, views: 0)
a4.items.create(name: 'Richard Nixon', group_id: 7, views: 0)
a4.items.create(name: 'Lyndon Baines Johnson', group_id: 7, views: 0)
a4.items.create(name: 'John Fitzgerald “J.F.” Kennedy', group_id: 7, views: 0)
a4.items.create(name: 'Dwight David “Ike” Eisenhower', group_id: 7, views: 0)
a4.items.create(name: 'Harry S. Truman', group_id: 7, views: 0)
a4.items.create(name: 'Franklin Delano Roosevelt', group_id: 7, views: 0)
a4.items.create(name: 'Herbert Hoover', group_id: 7, views: 0)
a4.items.create(name: 'Calvin Coolidge', group_id: 7, views: 0)
a4.items.create(name: 'Warren Gamaliel Harding', group_id: 7, views: 0)
a4.items.create(name: 'Woodrow Wilson', group_id: 7, views: 0)
a4.items.create(name: 'William Howard Taft', group_id: 7, views: 0)
a4.items.create(name: 'Theodore Roosevelt', group_id: 7, views: 0)
a4.items.create(name: 'William McKinley', group_id: 7, views: 0)
a4.items.create(name: 'Grover Cleveland', group_id: 7, views: 0)
a4.items.create(name: 'Benjamin Harrison', group_id: 7, views: 0)
a4.items.create(name: 'Grover Cleveland', group_id: 7, views: 0)
a4.items.create(name: 'Chester Alan Arthur', group_id: 7, views: 0)
a4.items.create(name: 'James Abram Garf', group_id: 7, views: 0)
a4.items.create(name: 'Rutherford Birchard Hayes', group_id: 7, views: 0)
a4.items.create(name: 'Ulysses S. Grant', group_id: 7, views: 0)
a4.items.create(name: 'Andrew Johnson', group_id: 7, views: 0)
a4.items.create(name: 'Abraham Lincoln', group_id: 7, views: 0)
a4.items.create(name: 'James Buchanan', group_id: 7, views: 0)
a4.items.create(name: 'Franklin Pierce', group_id: 7, views: 0)
a4.items.create(name: 'Millard Fillmore', group_id: 7, views: 0)
a4.items.create(name: 'Zachary Taylor', group_id: 7, views: 0)
a4.items.create(name: 'James Knock Polk', group_id: 7, views: 0)
a4.items.create(name: 'John Tyler', group_id: 7, views: 0)
a4.items.create(name: 'William Henry Harr', group_id: 7, views: 0)
a4.items.create(name: 'Martin van Buren', group_id: 7, views: 0)
a4.items.create(name: 'Andrew Jackson', group_id: 7, views: 0)
a4.items.create(name: 'John Quincy Adams', group_id: 7, views: 0)
a4.items.create(name: 'James Monroe', group_id: 7, views: 0)
a4.items.create(name: 'James Madison', group_id: 7, views: 0)
a4.items.create(name: 'Thomas Jefferson', group_id: 7, views: 0)
a4.items.create(name: 'John Adams', group_id: 7, views: 0)
a4.items.create(name: 'George Washington', group_id: 7, views: 0)

a4.items.create(name: 'Alabama', group_id: 8, views: 0)
a4.items.create(name: 'Alaska', group_id: 8, views: 0)
a4.items.create(name: 'Arizona', group_id: 8, views: 0)
a4.items.create(name: 'Arkansas', group_id: 8, views: 0)
a4.items.create(name: 'California', group_id: 8, views: 0)
a4.items.create(name: 'Colorado', group_id: 8, views: 0)
a4.items.create(name: 'Connecticut', group_id: 8, views: 0)
a4.items.create(name: 'Delaware', group_id: 8, views: 0)
a4.items.create(name: 'Florida', group_id: 8, views: 0)
a4.items.create(name: 'Georgia', group_id: 8, views: 0)
a4.items.create(name: 'Hawaii', group_id: 8, views: 0)
a4.items.create(name: 'Idaho', group_id: 8, views: 0)
a4.items.create(name: 'Illinois', group_id: 8, views: 0)
a4.items.create(name: 'Indiana', group_id: 8, views: 0)
a4.items.create(name: 'Iowa', group_id: 8, views: 0)
a4.items.create(name: 'Kansas', group_id: 8, views: 0)
a4.items.create(name: 'Kentucky', group_id: 8, views: 0)
a4.items.create(name: 'Louisiana', group_id: 8, views: 0)
a4.items.create(name: 'Maine', group_id: 8, views: 0)
a4.items.create(name: 'Maryland', group_id: 8, views: 0)
a4.items.create(name: 'Massachusetts', group_id: 8, views: 0)
a4.items.create(name: 'Michigan', group_id: 8, views: 0)
a4.items.create(name: 'Minnesota', group_id: 8, views: 0)
a4.items.create(name: 'Mississippi', group_id: 8, views: 0)
a4.items.create(name: 'Missouri', group_id: 8, views: 0)
a4.items.create(name: 'Montana', group_id: 8, views: 0)
a4.items.create(name: 'North Carolina', group_id: 8, views: 0)
a4.items.create(name: 'Nebraska', group_id: 8, views: 0)
a4.items.create(name: 'Nevada', group_id: 8, views: 0)
a4.items.create(name: 'New Hampshire', group_id: 8, views: 0)
a4.items.create(name: 'New Jersey', group_id: 8, views: 0)
a4.items.create(name: 'New Mexico', group_id: 8, views: 0)
a4.items.create(name: 'New York', group_id: 8, views: 0)
a4.items.create(name: 'North Dakota', group_id: 8, views: 0)
a4.items.create(name: 'Ohio', group_id: 8, views: 0)
a4.items.create(name: 'Oklahoma', group_id: 8, views: 0)
a4.items.create(name: 'Oregon', group_id: 8, views: 0)
a4.items.create(name: 'Pennsylvania', group_id: 8, views: 0)
a4.items.create(name: 'Rhode Island', group_id: 8, views: 0)
a4.items.create(name: 'South Carolina', group_id: 8, views: 0)
a4.items.create(name: 'South Dakota', group_id: 8, views: 0)
a4.items.create(name: 'Tennessee', group_id: 8, views: 0)
a4.items.create(name: 'Texas', group_id: 8, views: 0)
a4.items.create(name: 'Utah', group_id: 8, views: 0)
a4.items.create(name: 'Vermont', group_id: 8, views: 0)
a4.items.create(name: 'Virginia', group_id: 8, views: 0)
a4.items.create(name: 'Washington', group_id: 8, views: 0)
a4.items.create(name: 'West Virginia', group_id: 8, views: 0)
a4.items.create(name: 'Wisconsin', group_id: 8, views: 0)
a4.items.create(name: 'Wyoming', group_id: 8, views: 0)

a4.items.create(name: 'Alberta', group_id: 9, views: 0)
a4.items.create(name: 'British Columbia', group_id: 9, views: 0)
a4.items.create(name: 'Manitoba', group_id: 9, views: 0)
a4.items.create(name: 'New Brunswick', group_id: 9, views: 0)
a4.items.create(name: 'Newfoundland and Labrador', group_id: 9, views: 0)
a4.items.create(name: 'Nova Scotia', group_id: 9, views: 0)
a4.items.create(name: 'Ontario', group_id: 9, views: 0)
a4.items.create(name: 'Prince Edward Island', group_id: 9, views: 0)
a4.items.create(name: 'Quebec', group_id: 9, views: 0)
a4.items.create(name: 'Saskatchewan', group_id: 9, views: 0)

a5.items.create(name: 'Jupiter', group_id: 10, views: 0)
a5.items.create(name: 'Juno', group_id: 10, views: 0)
a5.items.create(name: 'Aurora', group_id: 10, views: 0)
a5.items.create(name: 'Bacchus', group_id: 10, views: 0)
a5.items.create(name: 'Ceres', group_id: 10, views: 0)
a5.items.create(name: 'Cupid', group_id: 10, views: 0)
a5.items.create(name: 'Diana', group_id: 10, views: 0)
a5.items.create(name: 'Faunus', group_id: 10, views: 0)
a5.items.create(name: 'Flora', group_id: 10, views: 0)
a5.items.create(name: 'Fortuna', group_id: 10, views: 0)
a5.items.create(name: 'Janus', group_id: 10, views: 0)
a5.items.create(name: 'Justitia', group_id: 10, views: 0)
a5.items.create(name: 'Maia', group_id: 10, views: 0)
a5.items.create(name: 'Mars', group_id: 10, views: 0)
a5.items.create(name: 'Mercury', group_id: 10, views: 0)
a5.items.create(name: 'Minerva', group_id: 10, views: 0)
a5.items.create(name: 'Neptune', group_id: 10, views: 0)
a5.items.create(name: 'Pluto', group_id: 10, views: 0)
a5.items.create(name: 'Plutus', group_id: 10, views: 0)
a5.items.create(name: 'Pomona', group_id: 10, views: 0)
a5.items.create(name: 'Proserpine', group_id: 10, views: 0)
a5.items.create(name: 'Saturn', group_id: 10, views: 0)
a5.items.create(name: 'Tellus', group_id: 10, views: 0)
a5.items.create(name: 'Uranus', group_id: 10, views: 0)
a5.items.create(name: 'Venus', group_id: 10, views: 0)
a5.items.create(name: 'Vesta', group_id: 10, views: 0)
a5.items.create(name: 'Vulcan', group_id: 10, views: 0)

a5.items.create(name: "Argo", group_id: 11, views: 0)
a5.items.create(name: "The Artist", group_id: 11, views: 0)
a5.items.create(name: "The King's Speech", group_id: 11, views: 0)
a5.items.create(name: "The Hurt Locker", group_id: 11, views: 0)
a5.items.create(name: "Slumdog Millionaire", group_id: 11, views: 0)
a5.items.create(name: "No Country for Old Men", group_id: 11, views: 0)
a5.items.create(name: "The Departed", group_id: 11, views: 0)
a5.items.create(name: "Crash", group_id: 11, views: 0)
a5.items.create(name: "Million Dollar Baby", group_id: 11, views: 0)
a5.items.create(name: "The Lord of the Rings: The Return of the King", group_id: 11, views: 0)
a5.items.create(name: "Chicago", group_id: 11, views: 0)
a5.items.create(name: "A Beautiful Mind", group_id: 11, views: 0)
a5.items.create(name: "Gladiator", group_id: 11, views: 0)
a5.items.create(name: "American Beauty", group_id: 11, views: 0)
a5.items.create(name: "Shakespeare in Love", group_id: 11, views: 0)
a5.items.create(name: "Titanic", group_id: 11, views: 0)
a5.items.create(name: "The English Patient", group_id: 11, views: 0)
a5.items.create(name: "Braveheart", group_id: 11, views: 0)
a5.items.create(name: "Forrest Gump", group_id: 11, views: 0)
a5.items.create(name: "Schindler’s List", group_id: 11, views: 0)
a5.items.create(name: "Unforgiven", group_id: 11, views: 0)
a5.items.create(name: "The Silence of the Lambs", group_id: 11, views: 0)
a5.items.create(name: "Dances With Wolves", group_id: 11, views: 0)
a5.items.create(name: "Driving Miss Daisy", group_id: 11, views: 0)
a5.items.create(name: "Rain Man", group_id: 11, views: 0)
a5.items.create(name: "The Last Emperor", group_id: 11, views: 0)
a5.items.create(name: "Platoon", group_id: 11, views: 0)
a5.items.create(name: "Out of Africa", group_id: 11, views: 0)
a5.items.create(name: "Amadeus", group_id: 11, views: 0)
a5.items.create(name: "Terms of Endearment", group_id: 11, views: 0)
a5.items.create(name: "Gandhi", group_id: 11, views: 0)
a5.items.create(name: "Chariots of Fire", group_id: 11, views: 0)
a5.items.create(name: "Ordinary People", group_id: 11, views: 0)
a5.items.create(name: "Kramer vs. Kramer", group_id: 11, views: 0)
a5.items.create(name: "The Deer Hunter", group_id: 11, views: 0)
a5.items.create(name: "Annie Hall", group_id: 11, views: 0)
a5.items.create(name: "Rocky", group_id: 11, views: 0)
a5.items.create(name: "One Flew over the Cuckoo's Nest", group_id: 11, views: 0)
a5.items.create(name: "The Godfather Part II", group_id: 11, views: 0)
a5.items.create(name: "The Sting", group_id: 11, views: 0)
a5.items.create(name: "The Godfather", group_id: 11, views: 0)
a5.items.create(name: "The French Connection", group_id: 11, views: 0)
a5.items.create(name: "Patton", group_id: 11, views: 0)
a5.items.create(name: "Midnight Cowboy", group_id: 11, views: 0)
a5.items.create(name: "Oliver!", group_id: 11, views: 0)
a5.items.create(name: "In the Heat of the Night", group_id: 11, views: 0)
a5.items.create(name: "A Man for All Seasons", group_id: 11, views: 0)
a5.items.create(name: "The Sound of Music", group_id: 11, views: 0)
a5.items.create(name: "My Fair Lady", group_id: 11, views: 0)
a5.items.create(name: "Tom Jones", group_id: 11, views: 0)
a5.items.create(name: "Lawrence of Arabia", group_id: 11, views: 0)
a5.items.create(name: "West Side Story", group_id: 11, views: 0)
a5.items.create(name: "The Apartment", group_id: 11, views: 0)
a5.items.create(name: "Ben-Hur", group_id: 11, views: 0)
a5.items.create(name: "Gigi", group_id: 11, views: 0)
a5.items.create(name: "The Bridge on the River Kwai", group_id: 11, views: 0)
a5.items.create(name: "Around the World in 80 Days", group_id: 11, views: 0)
a5.items.create(name: "Marty", group_id: 11, views: 0)
a5.items.create(name: "On the Waterfront", group_id: 11, views: 0)
a5.items.create(name: "From Here to Eternity", group_id: 11, views: 0)
a5.items.create(name: "The Greatest Show on Earth", group_id: 11, views: 0)
a5.items.create(name: "An American in Paris", group_id: 11, views: 0)
a5.items.create(name: "All About Eve", group_id: 11, views: 0)
a5.items.create(name: "All the Kings Men", group_id: 11, views: 0)
a5.items.create(name: "Hamlet", group_id: 11, views: 0)
a5.items.create(name: "Gentleman's Agreement", group_id: 11, views: 0)
a5.items.create(name: "The Best Years of Our Lives", group_id: 11, views: 0)
a5.items.create(name: "The Lost Weekend", group_id: 11, views: 0)
a5.items.create(name: "Going My Way", group_id: 11, views: 0)
a5.items.create(name: "Casablanca", group_id: 11, views: 0)
a5.items.create(name: "Mrs. Miniver", group_id: 11, views: 0)
a5.items.create(name: "How Green Was My Valley", group_id: 11, views: 0)
a5.items.create(name: "Rebecca", group_id: 11, views: 0)
a5.items.create(name: "Gone with the Wind", group_id: 11, views: 0)
a5.items.create(name: "You Can't Take It with You", group_id: 11, views: 0)
a5.items.create(name: "The Life of Emile Zola", group_id: 11, views: 0)
a5.items.create(name: "The Great Ziegfeld", group_id: 11, views: 0)
a5.items.create(name: "Mutiny on the Bounty", group_id: 11, views: 0)
a5.items.create(name: "It Happened One Night", group_id: 11, views: 0)
a5.items.create(name: "Cavalcade", group_id: 11, views: 0)
a5.items.create(name: "Grand Hotel", group_id: 11, views: 0)
a5.items.create(name: "Cimarron", group_id: 11, views: 0)
a5.items.create(name: "All Quiet on the Western Front", group_id: 11, views: 0)
a5.items.create(name: "The Broadway Melody", group_id: 11, views: 0)
a5.items.create(name: "Wings", group_id: 11, views: 0)

a5.items.create(name: "A Visit From the Goon Squad", group_id: 12, views: 0)
a5.items.create(name: "Tinkers", group_id: 12, views: 0)
a5.items.create(name: "Olive Kitteridge", group_id: 12, views: 0)
a5.items.create(name: "The Brief Wondrous Life of Oscar Wao", group_id: 12, views: 0)
a5.items.create(name: "The Road", group_id: 12, views: 0)
a5.items.create(name: "March", group_id: 12, views: 0)
a5.items.create(name: "Gilead", group_id: 12, views: 0)
a5.items.create(name: "The Known World", group_id: 12, views: 0)
a5.items.create(name: "Middlesex", group_id: 12, views: 0)
a5.items.create(name: "Empire Falls", group_id: 12, views: 0)
a5.items.create(name: "The Amazing Adventures of Kavalier & Clay", group_id: 12, views: 0)
a5.items.create(name: "Interpreter of Meladies", group_id: 12, views: 0)
a5.items.create(name: "The Hours", group_id: 12, views: 0)
a5.items.create(name: "American Pastoral", group_id: 12, views: 0)
a5.items.create(name: "Martin Dressler: The Tale of An American Dreamer", group_id: 12, views: 0)
a5.items.create(name: "Independence Day", group_id: 12, views: 0)
a5.items.create(name: "The Stone Diaries", group_id: 12, views: 0)
a5.items.create(name: "The Shipping News", group_id: 12, views: 0)
a5.items.create(name: "A Good Scent from a Strange Mountain", group_id: 12, views: 0)
a5.items.create(name: "A Thousand Acres", group_id: 12, views: 0)
a5.items.create(name: "Rabbit at Rest", group_id: 12, views: 0)
a5.items.create(name: "The Mambo Kings Play Songs of Love", group_id: 12, views: 0)
a5.items.create(name: "Breathing Lessons", group_id: 12, views: 0)
a5.items.create(name: "Beloved", group_id: 12, views: 0)
a5.items.create(name: "A Summons to Memphis", group_id: 12, views: 0)
a5.items.create(name: "Lonesome Dove", group_id: 12, views: 0)
a5.items.create(name: "Foreign Affairs", group_id: 12, views: 0)
a5.items.create(name: "Ironweed", group_id: 12, views: 0)
a5.items.create(name: "The Color Purple", group_id: 12, views: 0)
a5.items.create(name: "Rabbit is Rich", group_id: 12, views: 0)
a5.items.create(name: "A Confederacy of Dunces", group_id: 12, views: 0)
a5.items.create(name: "The Executioner’s Song", group_id: 12, views: 0)

# groups

g1 = a1.groups.create(name: 'Days of the Week')
g2 = a1.groups.create(name: 'Months')
g3 = a2.groups.create(name: 'Wine bottle sizes')
g4 = a2.groups.create(name: 'Royal Peerage')
g5 = a3.groups.create(name: 'Signs of the Zodiac')

g6 = a3.groups.create(name: 'Poets Laureate')
g7 = a4.groups.create(name: 'US Presidents')
g8 = a4.groups.create(name: 'States of the United States')
g9 = a4.groups.create(name: 'Canadian Provinces')
g10 = a5.groups.create(name: 'Roman Deities')

g11 = a5.groups.create(name: 'Oscar Winning Films')
g12 = a5.groups.create(name: 'Pulitzer Prize Winning Novels')

# tags

a1.tags.create(name: 'Dates')
a1.tags.create(name: 'Food')
a1.tags.create(name: 'Drink')
a3.tags.create(name: 'People')
a4.tags.create(name: 'America')
a4.tags.create(name: 'USA')
a5.tags.create(name: 'Canada')
a2.tags.create(name: 'Films')
a2.tags.create(name: 'Novels')
a2.tags.create(name: 'Books')
a2.tags.create(name: 'Religion')

# group_tags

g1.GroupTags.create(tag_id: 1)
g2.GroupTags.create(tag_id: 1)
g3.GroupTags.create(tag_id: 2)
g3.GroupTags.create(tag_id: 3)
g4.GroupTags.create(tag_id: 4)
g5.GroupTags.create(tag_id: 1)
g5.GroupTags.create(tag_id: 1)
g6.GroupTags.create(tag_id: 4)
g7.GroupTags.create(tag_id: 4)
g7.GroupTags.create(tag_id: 5)
g7.GroupTags.create(tag_id: 6)
g8.GroupTags.create(tag_id: 5)
g8.GroupTags.create(tag_id: 6)
g8.GroupTags.create(tag_id: 4)
g9.GroupTags.create(tag_id: 7)
g10.GroupTags.create(tag_id: 11)
g11.GroupTags.create(tag_id: 8)
g12.GroupTags.create(tag_id: 10)
