# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

# authors

a1 = Author.create(name: 'Alice')
a2 = Author.create(name: 'Bob')
a3 = Author.create(name: 'Cindy')
a4 = Author.create(name: 'Donald')
a5 = Author.create(name: 'Edith')

# items

a1.items.create(name: 'Monday', group_id: 1, views: 0)
a1.items.create(name: 'Tuesday', group_id: 1, views: 0)
a1.items.create(name: 'Wednesday', group_id: 1, views: 0)
a1.items.create(name: 'Thursday', group_id: 1, views: 0)
a1.items.create(name: 'Friday', group_id: 1, views: 0)
a1.items.create(name: 'Saturday', group_id: 1, views: 0)
a1.items.create(name: 'Sunday', group_id: 1, views: 0)

a1.items.create(name: 'January', group_id: 2, views: 0)
a1.items.create(name: 'February', group_id: 2, views: 0)
a1.items.create(name: 'March', group_id: 2, views: 0)
a1.items.create(name: 'April', group_id: 2, views: 0)
a1.items.create(name: 'May', group_id: 2, views: 0)
a1.items.create(name: 'June', group_id: 2, views: 0)
a1.items.create(name: 'July', group_id: 2, views: 0)
a1.items.create(name: 'August', group_id: 2, views: 0)
a1.items.create(name: 'September', group_id: 2, views: 0)
a1.items.create(name: 'October', group_id: 2, views: 0)
a1.items.create(name: 'November', group_id: 2, views: 0)
a1.items.create(name: 'December', group_id: 2, views: 0)

a2.items.create(name: 'Piccolo', group_id: 3, views: 0)
a2.items.create(name: 'Quarter', group_id: 3, views: 0)
a2.items.create(name: 'Chopine', group_id: 3, views: 0)
a2.items.create(name: 'Demi', group_id: 3, views: 0)
a2.items.create(name: 'Tenth', group_id: 3, views: 0)
a2.items.create(name: 'Jennie', group_id: 3, views: 0)
a2.items.create(name: 'Clavelin', group_id: 3, views: 0)
a2.items.create(name: 'Standard', group_id: 3, views: 0)
a2.items.create(name: 'Fifth', group_id: 3, views: 0)
a2.items.create(name: 'Litre', group_id: 3, views: 0)
a2.items.create(name: 'Magnum', group_id: 3, views: 0)
a2.items.create(name: 'Marie Jeanne', group_id: 3, views: 0)
a2.items.create(name: 'Jeroboam', group_id: 3, views: 0)
a2.items.create(name: 'Rehoboam', group_id: 3, views: 0)
a2.items.create(name: 'Imperial', group_id: 3, views: 0)
a2.items.create(name: 'Methuselah', group_id: 3, views: 0)
a2.items.create(name: 'Salmanazar', group_id: 3, views: 0)
a2.items.create(name: 'Nebuchadnezzar', group_id: 3, views: 0)
a2.items.create(name: 'Melchior', group_id: 3, views: 0)
a2.items.create(name: 'Solomon', group_id: 3, views: 0)
a2.items.create(name: 'Sovereign', group_id: 3, views: 0)
a2.items.create(name: 'Goliath', group_id: 3, views: 0)
a2.items.create(name: 'Midas', group_id: 3, views: 0)

a2.items.create(name: 'King', group_id: 4, views: 0)
a2.items.create(name: 'Queen', group_id: 4, views: 0)
a2.items.create(name: 'Royal Duke', group_id: 4, views: 0)
a2.items.create(name: 'Duchess', group_id: 4, views: 0)
a2.items.create(name: 'Archbishop', group_id: 4, views: 0)
a2.items.create(name: 'Duke', group_id: 4, views: 0)
a2.items.create(name: 'Duchess', group_id: 4, views: 0)
a2.items.create(name: 'Marquess', group_id: 4, views: 0)
a2.items.create(name: 'Marchioness', group_id: 4, views: 0)
a2.items.create(name: 'Earl', group_id: 4, views: 0)
a2.items.create(name: 'Countess', group_id: 4, views: 0)
a2.items.create(name: 'Viscount', group_id: 4, views: 0)
a2.items.create(name: 'Viscountess', group_id: 4, views: 0)
a2.items.create(name: 'Bishop', group_id: 4, views: 0)
a2.items.create(name: 'Baron', group_id: 4, views: 0)
a2.items.create(name: 'Baroness', group_id: 4, views: 0)

a3.items.create(name: 'Aries', group_id: 5, views: 0)
a3.items.create(name: 'Taurus', group_id: 5, views: 0)
a3.items.create(name: 'Gemini', group_id: 5, views: 0)
a3.items.create(name: 'Cancer', group_id: 5, views: 0)
a3.items.create(name: 'Leo', group_id: 5, views: 0)
a3.items.create(name: 'Virgo', group_id: 5, views: 0)
a3.items.create(name: 'Libra', group_id: 5, views: 0)
a3.items.create(name: 'Scorpio', group_id: 5, views: 0)
a3.items.create(name: 'Sagittarius', group_id: 5, views: 0)
a3.items.create(name: 'Capricorn', group_id: 5, views: 0)
a3.items.create(name: 'Aquarius', group_id: 5, views: 0)
a3.items.create(name: 'Pisces', group_id: 5, views: 0)

a3.items.create(name: "Carol Ann Duffy", group_id: 6, views: 0)
a3.items.create(name: "Andrew Motion", group_id: 6, views: 0)
a3.items.create(name: "Edward (Ted) Hughes", group_id: 6, views: 0)
a3.items.create(name: "Sir John Betjeman", group_id: 6, views: 0)
a3.items.create(name: "Cecil Day Lewis", group_id: 6, views: 0)
a3.items.create(name: "John Masefield", group_id: 6, views: 0)
a3.items.create(name: "Robert Bridges", group_id: 6, views: 0)
a3.items.create(name: "Alfred Austin", group_id: 6, views: 0)
a3.items.create(name: "Alfred Lord Tennyson", group_id: 6, views: 0)
a3.items.create(name: "William Wordsworth", group_id: 6, views: 0)
a3.items.create(name: "Robert Southey", group_id: 6, views: 0)
a3.items.create(name: "Henry James Pye", group_id: 6, views: 0)
a3.items.create(name: "Thomas Warton", group_id: 6, views: 0)
a3.items.create(name: "William Whiteheed", group_id: 6, views: 0)
a3.items.create(name: "Colley Cibber", group_id: 6, views: 0)
a3.items.create(name: "Rev. Laurence Eusden", group_id: 6, views: 0)
a3.items.create(name: "Nicholas Rowe", group_id: 6, views: 0)
a3.items.create(name: "Nathan Tate", group_id: 6, views: 0)
a3.items.create(name: "Thomas Shadwall", group_id: 6, views: 0)
a3.items.create(name: "John Dryden", group_id: 6, views: 0)
a3.items.create(name: "Sir William d’Avenant", group_id: 6, views: 0)
a3.items.create(name: "Ben Jonson", group_id: 6, views: 0)
a3.items.create(name: "Samuel Daniel", group_id: 6, views: 0)

a4.items.create(name: 'Barack Hussein Obama', group_id: 7, views: 0)
a4.items.create(name: 'George Walker “W” Bush', group_id: 7, views: 0)
a4.items.create(name: 'William (Bill) Jefferson Clinton', group_id: 7, views: 0)
a4.items.create(name: 'George Herbert Walker Bush', group_id: 7, views: 0)
a4.items.create(name: 'Ronald Reagan', group_id: 7, views: 0)
a4.items.create(name: 'James (Jimmy) Carter', group_id: 7, views: 0)
a4.items.create(name: 'Gerald Ford', group_id: 7, views: 0)
a4.items.create(name: 'Richard Nixon', group_id: 7, views: 0)
a4.items.create(name: 'Lyndon Baines Johnson', group_id: 7, views: 0)
a4.items.create(name: 'John Fitzgerald “J.F.” Kennedy', group_id: 7, views: 0)
a4.items.create(name: 'Dwight David “Ike” Eisenhower', group_id: 7, views: 0)
a4.items.create(name: 'Harry S. Truman', group_id: 7, views: 0)
a4.items.create(name: 'Franklin Delano Roosevelt', group_id: 7, views: 0)
a4.items.create(name: 'Herbert Hoover', group_id: 7, views: 0)
a4.items.create(name: 'Calvin Coolidge', group_id: 7, views: 0)
a4.items.create(name: 'Warren Gamaliel Harding', group_id: 7, views: 0)
a4.items.create(name: 'Woodrow Wilson', group_id: 7, views: 0)
a4.items.create(name: 'William Howard Taft', group_id: 7, views: 0)
a4.items.create(name: 'Theodore Roosevelt', group_id: 7, views: 0)
a4.items.create(name: 'William McKinley', group_id: 7, views: 0)
a4.items.create(name: 'Grover Cleveland', group_id: 7, views: 0)
a4.items.create(name: 'Benjamin Harrison', group_id: 7, views: 0)
a4.items.create(name: 'Grover Cleveland', group_id: 7, views: 0)
a4.items.create(name: 'Chester Alan Arthur', group_id: 7, views: 0)
a4.items.create(name: 'James Abram Garf', group_id: 7, views: 0)
a4.items.create(name: 'Rutherford Birchard Hayes', group_id: 7, views: 0)
a4.items.create(name: 'Ulysses S. Grant', group_id: 7, views: 0)
a4.items.create(name: 'Andrew Johnson', group_id: 7, views: 0)
a4.items.create(name: 'Abraham Lincoln', group_id: 7, views: 0)
a4.items.create(name: 'James Buchanan', group_id: 7, views: 0)
a4.items.create(name: 'Franklin Pierce', group_id: 7, views: 0)
a4.items.create(name: 'Millard Fillmore', group_id: 7, views: 0)
a4.items.create(name: 'Zachary Taylor', group_id: 7, views: 0)
a4.items.create(name: 'James Knock Polk', group_id: 7, views: 0)
a4.items.create(name: 'John Tyler', group_id: 7, views: 0)
a4.items.create(name: 'William Henry Harr', group_id: 7, views: 0)
a4.items.create(name: 'Martin van Buren', group_id: 7, views: 0)
a4.items.create(name: 'Andrew Jackson', group_id: 7, views: 0)
a4.items.create(name: 'John Quincy Adams', group_id: 7, views: 0)
a4.items.create(name: 'James Monroe', group_id: 7, views: 0)
a4.items.create(name: 'James Madison', group_id: 7, views: 0)
a4.items.create(name: 'Thomas Jefferson', group_id: 7, views: 0)
a4.items.create(name: 'John Adams', group_id: 7, views: 0)
a4.items.create(name: 'George Washington', group_id: 7, views: 0)

a4.items.create(name: 'Alabama', group_id: 8, views: 0)
a4.items.create(name: 'Alaska', group_id: 8, views: 0)
a4.items.create(name: 'Arizona', group_id: 8, views: 0)
a4.items.create(name: 'Arkansas', group_id: 8, views: 0)
a4.items.create(name: 'California', group_id: 8, views: 0)
a4.items.create(name: 'Colorado', group_id: 8, views: 0)
a4.items.create(name: 'Connecticut', group_id: 8, views: 0)
a4.items.create(name: 'Delaware', group_id: 8, views: 0)
a4.items.create(name: 'Florida', group_id: 8, views: 0)
a4.items.create(name: 'Georgia', group_id: 8, views: 0)
a4.items.create(name: 'Hawaii', group_id: 8, views: 0)
a4.items.create(name: 'Idaho', group_id: 8, views: 0)
a4.items.create(name: 'Illinois', group_id: 8, views: 0)
a4.items.create(name: 'Indiana', group_id: 8, views: 0)
a4.items.create(name: 'Iowa', group_id: 8, views: 0)
a4.items.create(name: 'Kansas', group_id: 8, views: 0)
a4.items.create(name: 'Kentucky', group_id: 8, views: 0)
a4.items.create(name: 'Louisiana', group_id: 8, views: 0)
a4.items.create(name: 'Maine', group_id: 8, views: 0)
a4.items.create(name: 'Maryland', group_id: 8, views: 0)
a4.items.create(name: 'Massachusetts', group_id: 8, views: 0)
a4.items.create(name: 'Michigan', group_id: 8, views: 0)
a4.items.create(name: 'Minnesota', group_id: 8, views: 0)
a4.items.create(name: 'Mississippi', group_id: 8, views: 0)
a4.items.create(name: 'Missouri', group_id: 8, views: 0)
a4.items.create(name: 'Montana', group_id: 8, views: 0)
a4.items.create(name: 'North Carolina', group_id: 8, views: 0)
a4.items.create(name: 'Nebraska', group_id: 8, views: 0)
a4.items.create(name: 'Nevada', group_id: 8, views: 0)
a4.items.create(name: 'New Hampshire', group_id: 8, views: 0)
a4.items.create(name: 'New Jersey', group_id: 8, views: 0)
a4.items.create(name: 'New Mexico', group_id: 8, views: 0)
a4.items.create(name: 'New York', group_id: 8, views: 0)
a4.items.create(name: 'North Dakota', group_id: 8, views: 0)
a4.items.create(name: 'Ohio', group_id: 8, views: 0)
a4.items.create(name: 'Oklahoma', group_id: 8, views: 0)
a4.items.create(name: 'Oregon', group_id: 8, views: 0)
a4.items.create(name: 'Pennsylvania', group_id: 8, views: 0)
a4.items.create(name: 'Rhode Island', group_id: 8, views: 0)
a4.items.create(name: 'South Carolina', group_id: 8, views: 0)
a4.items.create(name: 'South Dakota', group_id: 8, views: 0)
a4.items.create(name: 'Tennessee', group_id: 8, views: 0)
a4.items.create(name: 'Texas', group_id: 8, views: 0)
a4.items.create(name: 'Utah', group_id: 8, views: 0)
a4.items.create(name: 'Vermont', group_id: 8, views: 0)
a4.items.create(name: 'Virginia', group_id: 8, views: 0)
a4.items.create(name: 'Washington', group_id: 8, views: 0)
a4.items.create(name: 'West Virginia', group_id: 8, views: 0)
a4.items.create(name: 'Wisconsin', group_id: 8, views: 0)
a4.items.create(name: 'Wyoming', group_id: 8, views: 0)

a4.items.create(name: 'Alberta', group_id: 9, views: 0)
a4.items.create(name: 'British Columbia', group_id: 9, views: 0)
a4.items.create(name: 'Manitoba', group_id: 9, views: 0)
a4.items.create(name: 'New Brunswick', group_id: 9, views: 0)
a4.items.create(name: 'Newfoundland and Labrador', group_id: 9, views: 0)
a4.items.create(name: 'Nova Scotia', group_id: 9, views: 0)
a4.items.create(name: 'Ontario', group_id: 9, views: 0)
a4.items.create(name: 'Prince Edward Island', group_id: 9, views: 0)
a4.items.create(name: 'Quebec', group_id: 9, views: 0)
a4.items.create(name: 'Saskatchewan', group_id: 9, views: 0)

# groups

a1.groups.create(name: 'Days of the Week')
a1.groups.create(name: 'Months')
a2.groups.create(name: 'Wine bottle sizes')
a2.groups.create(name: 'Royal Peerage')
a3.groups.create(name: 'Signs of the Zodiac')

a3.groups.create(name: 'Poets Laureate')
a4.groups.create(name: 'US Presidents')
a4.groups.create(name: 'States of the United States')
a4.groups.create(name: 'Canadian Provinces')

a5.groups.create(name: 'Roman Deities')
a5.groups.create(name: 'Oscar Winning Films')
a5.groups.create(name: 'Pulitzer Prize Winning Novels')

# tags



# group_tags